/*******************************************************************************
* Copyright 2021 Intel Corporation
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions
* and limitations under the License.
*
*
* SPDX-License-Identifier: Apache-2.0
*******************************************************************************/

oneapi::math::lapack::LAPACK_BACKEND::gebrd, oneapi::math::lapack::LAPACK_BACKEND::gebrd,
    oneapi::math::lapack::LAPACK_BACKEND::gebrd, oneapi::math::lapack::LAPACK_BACKEND::gebrd,
    oneapi::math::lapack::LAPACK_BACKEND::gerqf, oneapi::math::lapack::LAPACK_BACKEND::gerqf,
    oneapi::math::lapack::LAPACK_BACKEND::gerqf, oneapi::math::lapack::LAPACK_BACKEND::gerqf,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf, oneapi::math::lapack::LAPACK_BACKEND::geqrf,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf, oneapi::math::lapack::LAPACK_BACKEND::geqrf,
    oneapi::math::lapack::LAPACK_BACKEND::getrf, oneapi::math::lapack::LAPACK_BACKEND::getrf,
    oneapi::math::lapack::LAPACK_BACKEND::getrf, oneapi::math::lapack::LAPACK_BACKEND::getrf,
    oneapi::math::lapack::LAPACK_BACKEND::getri, oneapi::math::lapack::LAPACK_BACKEND::getri,
    oneapi::math::lapack::LAPACK_BACKEND::getri, oneapi::math::lapack::LAPACK_BACKEND::getri,
    oneapi::math::lapack::LAPACK_BACKEND::getrs, oneapi::math::lapack::LAPACK_BACKEND::getrs,
    oneapi::math::lapack::LAPACK_BACKEND::getrs, oneapi::math::lapack::LAPACK_BACKEND::getrs,
    oneapi::math::lapack::LAPACK_BACKEND::gesvd, oneapi::math::lapack::LAPACK_BACKEND::gesvd,
    oneapi::math::lapack::LAPACK_BACKEND::gesvd, oneapi::math::lapack::LAPACK_BACKEND::gesvd,
    oneapi::math::lapack::LAPACK_BACKEND::heevd, oneapi::math::lapack::LAPACK_BACKEND::heevd,
    oneapi::math::lapack::LAPACK_BACKEND::hegvd, oneapi::math::lapack::LAPACK_BACKEND::hegvd,
    oneapi::math::lapack::LAPACK_BACKEND::hetrd, oneapi::math::lapack::LAPACK_BACKEND::hetrd,
    oneapi::math::lapack::LAPACK_BACKEND::hetrf, oneapi::math::lapack::LAPACK_BACKEND::hetrf,
    oneapi::math::lapack::LAPACK_BACKEND::orgbr, oneapi::math::lapack::LAPACK_BACKEND::orgbr,
    oneapi::math::lapack::LAPACK_BACKEND::orgqr, oneapi::math::lapack::LAPACK_BACKEND::orgqr,
    oneapi::math::lapack::LAPACK_BACKEND::orgtr, oneapi::math::lapack::LAPACK_BACKEND::orgtr,
    oneapi::math::lapack::LAPACK_BACKEND::ormtr, oneapi::math::lapack::LAPACK_BACKEND::ormtr,
    oneapi::math::lapack::LAPACK_BACKEND::ormrq, oneapi::math::lapack::LAPACK_BACKEND::ormrq,
    oneapi::math::lapack::LAPACK_BACKEND::ormqr, oneapi::math::lapack::LAPACK_BACKEND::ormqr,
    oneapi::math::lapack::LAPACK_BACKEND::potrf, oneapi::math::lapack::LAPACK_BACKEND::potrf,
    oneapi::math::lapack::LAPACK_BACKEND::potrf, oneapi::math::lapack::LAPACK_BACKEND::potrf,
    oneapi::math::lapack::LAPACK_BACKEND::potri, oneapi::math::lapack::LAPACK_BACKEND::potri,
    oneapi::math::lapack::LAPACK_BACKEND::potri, oneapi::math::lapack::LAPACK_BACKEND::potri,
    oneapi::math::lapack::LAPACK_BACKEND::potrs, oneapi::math::lapack::LAPACK_BACKEND::potrs,
    oneapi::math::lapack::LAPACK_BACKEND::potrs, oneapi::math::lapack::LAPACK_BACKEND::potrs,
    oneapi::math::lapack::LAPACK_BACKEND::syevd, oneapi::math::lapack::LAPACK_BACKEND::syevd,
    oneapi::math::lapack::LAPACK_BACKEND::sygvd, oneapi::math::lapack::LAPACK_BACKEND::sygvd,
    oneapi::math::lapack::LAPACK_BACKEND::sytrd, oneapi::math::lapack::LAPACK_BACKEND::sytrd,
    oneapi::math::lapack::LAPACK_BACKEND::sytrf, oneapi::math::lapack::LAPACK_BACKEND::sytrf,
    oneapi::math::lapack::LAPACK_BACKEND::sytrf, oneapi::math::lapack::LAPACK_BACKEND::sytrf,
    oneapi::math::lapack::LAPACK_BACKEND::trtrs, oneapi::math::lapack::LAPACK_BACKEND::trtrs,
    oneapi::math::lapack::LAPACK_BACKEND::trtrs, oneapi::math::lapack::LAPACK_BACKEND::trtrs,
    oneapi::math::lapack::LAPACK_BACKEND::ungbr, oneapi::math::lapack::LAPACK_BACKEND::ungbr,
    oneapi::math::lapack::LAPACK_BACKEND::ungqr, oneapi::math::lapack::LAPACK_BACKEND::ungqr,
    oneapi::math::lapack::LAPACK_BACKEND::ungtr, oneapi::math::lapack::LAPACK_BACKEND::ungtr,
    oneapi::math::lapack::LAPACK_BACKEND::unmrq, oneapi::math::lapack::LAPACK_BACKEND::unmrq,
    oneapi::math::lapack::LAPACK_BACKEND::unmqr, oneapi::math::lapack::LAPACK_BACKEND::unmqr,
    oneapi::math::lapack::LAPACK_BACKEND::unmtr, oneapi::math::lapack::LAPACK_BACKEND::unmtr,
    oneapi::math::lapack::LAPACK_BACKEND::gebrd, oneapi::math::lapack::LAPACK_BACKEND::gebrd,
    oneapi::math::lapack::LAPACK_BACKEND::gebrd, oneapi::math::lapack::LAPACK_BACKEND::gebrd,
    oneapi::math::lapack::LAPACK_BACKEND::gerqf, oneapi::math::lapack::LAPACK_BACKEND::gerqf,
    oneapi::math::lapack::LAPACK_BACKEND::gerqf, oneapi::math::lapack::LAPACK_BACKEND::gerqf,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf, oneapi::math::lapack::LAPACK_BACKEND::geqrf,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf, oneapi::math::lapack::LAPACK_BACKEND::geqrf,
    oneapi::math::lapack::LAPACK_BACKEND::getrf, oneapi::math::lapack::LAPACK_BACKEND::getrf,
    oneapi::math::lapack::LAPACK_BACKEND::getrf, oneapi::math::lapack::LAPACK_BACKEND::getrf,
    oneapi::math::lapack::LAPACK_BACKEND::getri, oneapi::math::lapack::LAPACK_BACKEND::getri,
    oneapi::math::lapack::LAPACK_BACKEND::getri, oneapi::math::lapack::LAPACK_BACKEND::getri,
    oneapi::math::lapack::LAPACK_BACKEND::getrs, oneapi::math::lapack::LAPACK_BACKEND::getrs,
    oneapi::math::lapack::LAPACK_BACKEND::getrs, oneapi::math::lapack::LAPACK_BACKEND::getrs,
    oneapi::math::lapack::LAPACK_BACKEND::gesvd, oneapi::math::lapack::LAPACK_BACKEND::gesvd,
    oneapi::math::lapack::LAPACK_BACKEND::gesvd, oneapi::math::lapack::LAPACK_BACKEND::gesvd,
    oneapi::math::lapack::LAPACK_BACKEND::heevd, oneapi::math::lapack::LAPACK_BACKEND::heevd,
    oneapi::math::lapack::LAPACK_BACKEND::hegvd, oneapi::math::lapack::LAPACK_BACKEND::hegvd,
    oneapi::math::lapack::LAPACK_BACKEND::hetrd, oneapi::math::lapack::LAPACK_BACKEND::hetrd,
    oneapi::math::lapack::LAPACK_BACKEND::hetrf, oneapi::math::lapack::LAPACK_BACKEND::hetrf,
    oneapi::math::lapack::LAPACK_BACKEND::orgbr, oneapi::math::lapack::LAPACK_BACKEND::orgbr,
    oneapi::math::lapack::LAPACK_BACKEND::orgqr, oneapi::math::lapack::LAPACK_BACKEND::orgqr,
    oneapi::math::lapack::LAPACK_BACKEND::orgtr, oneapi::math::lapack::LAPACK_BACKEND::orgtr,
    oneapi::math::lapack::LAPACK_BACKEND::ormtr, oneapi::math::lapack::LAPACK_BACKEND::ormtr,
    oneapi::math::lapack::LAPACK_BACKEND::ormrq, oneapi::math::lapack::LAPACK_BACKEND::ormrq,
    oneapi::math::lapack::LAPACK_BACKEND::ormqr, oneapi::math::lapack::LAPACK_BACKEND::ormqr,
    oneapi::math::lapack::LAPACK_BACKEND::potrf, oneapi::math::lapack::LAPACK_BACKEND::potrf,
    oneapi::math::lapack::LAPACK_BACKEND::potrf, oneapi::math::lapack::LAPACK_BACKEND::potrf,
    oneapi::math::lapack::LAPACK_BACKEND::potri, oneapi::math::lapack::LAPACK_BACKEND::potri,
    oneapi::math::lapack::LAPACK_BACKEND::potri, oneapi::math::lapack::LAPACK_BACKEND::potri,
    oneapi::math::lapack::LAPACK_BACKEND::potrs, oneapi::math::lapack::LAPACK_BACKEND::potrs,
    oneapi::math::lapack::LAPACK_BACKEND::potrs, oneapi::math::lapack::LAPACK_BACKEND::potrs,
    oneapi::math::lapack::LAPACK_BACKEND::syevd, oneapi::math::lapack::LAPACK_BACKEND::syevd,
    oneapi::math::lapack::LAPACK_BACKEND::sygvd, oneapi::math::lapack::LAPACK_BACKEND::sygvd,
    oneapi::math::lapack::LAPACK_BACKEND::sytrd, oneapi::math::lapack::LAPACK_BACKEND::sytrd,
    oneapi::math::lapack::LAPACK_BACKEND::sytrf, oneapi::math::lapack::LAPACK_BACKEND::sytrf,
    oneapi::math::lapack::LAPACK_BACKEND::sytrf, oneapi::math::lapack::LAPACK_BACKEND::sytrf,
    oneapi::math::lapack::LAPACK_BACKEND::trtrs, oneapi::math::lapack::LAPACK_BACKEND::trtrs,
    oneapi::math::lapack::LAPACK_BACKEND::trtrs, oneapi::math::lapack::LAPACK_BACKEND::trtrs,
    oneapi::math::lapack::LAPACK_BACKEND::ungbr, oneapi::math::lapack::LAPACK_BACKEND::ungbr,
    oneapi::math::lapack::LAPACK_BACKEND::ungqr, oneapi::math::lapack::LAPACK_BACKEND::ungqr,
    oneapi::math::lapack::LAPACK_BACKEND::ungtr, oneapi::math::lapack::LAPACK_BACKEND::ungtr,
    oneapi::math::lapack::LAPACK_BACKEND::unmrq, oneapi::math::lapack::LAPACK_BACKEND::unmrq,
    oneapi::math::lapack::LAPACK_BACKEND::unmqr, oneapi::math::lapack::LAPACK_BACKEND::unmqr,
    oneapi::math::lapack::LAPACK_BACKEND::unmtr, oneapi::math::lapack::LAPACK_BACKEND::unmtr,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::orgqr_batch,
    oneapi::math::lapack::LAPACK_BACKEND::orgqr_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::ungqr_batch,
    oneapi::math::lapack::LAPACK_BACKEND::ungqr_batch,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::orgqr_batch,
    oneapi::math::lapack::LAPACK_BACKEND::orgqr_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::ungqr_batch,
    oneapi::math::lapack::LAPACK_BACKEND::ungqr_batch,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::orgqr_batch,
    oneapi::math::lapack::LAPACK_BACKEND::orgqr_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch,
    oneapi::math::lapack::LAPACK_BACKEND::ungqr_batch,
    oneapi::math::lapack::LAPACK_BACKEND::ungqr_batch,
    oneapi::math::lapack::LAPACK_BACKEND::gebrd_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::gebrd_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::gebrd_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::gebrd_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::gerqf_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::gerqf_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::gerqf_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::gerqf_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::gesvd_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::gesvd_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::gesvd_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::gesvd_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::getri_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::getri_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::getri_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::getri_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::heevd_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::heevd_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::hegvd_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::hegvd_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::hetrd_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::hetrd_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::hetrf_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::hetrf_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::orgbr_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::orgbr_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::orgtr_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::orgtr_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::orgqr_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::orgqr_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::ormrq_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::ormrq_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::ormqr_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::ormqr_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::ormtr_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::ormtr_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::potri_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::potri_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::potri_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::potri_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::sytrf_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::sytrf_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::sytrf_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::sytrf_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::syevd_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::syevd_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::sygvd_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::sygvd_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::sytrd_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::sytrd_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::trtrs_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::trtrs_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::trtrs_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::trtrs_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::ungbr_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::ungbr_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::ungqr_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::ungqr_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::ungtr_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::ungtr_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::unmrq_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::unmrq_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::unmqr_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::unmqr_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::unmtr_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::unmtr_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::orgqr_batch_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::orgqr_batch_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::ungqr_batch_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::ungqr_batch_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::getrf_batch_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::getri_batch_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::getrs_batch_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::geqrf_batch_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::orgqr_batch_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::orgqr_batch_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::potrf_batch_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch_scratchpad_size<float>,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch_scratchpad_size<double>,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::potrs_batch_scratchpad_size<std::complex<double>>,
    oneapi::math::lapack::LAPACK_BACKEND::ungqr_batch_scratchpad_size<std::complex<float>>,
    oneapi::math::lapack::LAPACK_BACKEND::ungqr_batch_scratchpad_size<std::complex<double>>
