#!/bin/bash

clang-format -i   gbmv.cpp
clang-format -i   gbmv_usm.cpp
clang-format -i   gemv.cpp
clang-format -i   gemv_usm.cpp
clang-format -i   ger.cpp
clang-format -i   ger_usm.cpp
clang-format -i   gerc.cpp
clang-format -i   gerc_usm.cpp
clang-format -i   geru.cpp
clang-format -i   geru_usm.cpp
clang-format -i   hbmv.cpp
clang-format -i   hbmv_usm.cpp
clang-format -i   hemv.cpp
clang-format -i   hemv_usm.cpp
clang-format -i   her.cpp
clang-format -i   her2.cpp
clang-format -i   her2_usm.cpp
clang-format -i   her_usm.cpp
clang-format -i   hpmv.cpp
clang-format -i   hpmv_usm.cpp
clang-format -i   hpr.cpp
clang-format -i   hpr2.cpp
clang-format -i   hpr2_usm.cpp
clang-format -i   hpr_usm.cpp
clang-format -i   sbmv.cpp
clang-format -i   sbmv_usm.cpp
clang-format -i   spmv.cpp
clang-format -i   spmv_usm.cpp
clang-format -i   spr.cpp
clang-format -i   spr2.cpp
clang-format -i   spr2_usm.cpp
clang-format -i   spr_usm.cpp
clang-format -i   symv.cpp
clang-format -i   symv_usm.cpp
clang-format -i   syr.cpp
clang-format -i   syr2.cpp
clang-format -i   syr2_usm.cpp
clang-format -i   syr_usm.cpp
clang-format -i   tbmv.cpp
clang-format -i   tbmv_usm.cpp
clang-format -i   tbsv.cpp
clang-format -i   tbsv_usm.cpp
clang-format -i   tpmv.cpp
clang-format -i   tpmv_usm.cpp
clang-format -i   tpsv.cpp
clang-format -i   tpsv_usm.cpp
clang-format -i   trmv.cpp
clang-format -i   trmv_usm.cpp
clang-format -i   trsv.cpp
clang-format -i   trsv_usm.cpp
